name: Crosscompiler_with_sinaasappelsap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v2

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install cross-compiler
        run: sudo apt-get update && sudo apt-get install -y g++-arm-linux-gnueabihf

      - name: Compile C code
        run: arm-linux-gnueabihf-g++ helloworld.c -o helloworld-arm

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-code
          path: helloworld-arm 
